// @ts-check

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  // Auto-generate sidebar from docs folder structure
  helpSidebar: [{type: 'autogenerated', dirName: '.'}],
};

export default sidebars;
